/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miguel.reto5.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import miguel.reto5.controller.ReportesController;
import miguel.reto5.model.vo.DeudasPorProyectoVo;

/**
 *
 * @author usuario
 */
public class ReportesViewGuiConsulta2 extends javax.swing.JFrame {

    /**
     * Creates new form ReportesViewGuiConsulta2
     */
    public ReportesViewGuiConsulta2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        Btncargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtLimiInferior = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        consulta1 = new javax.swing.JMenuItem();
        consulta2 = new javax.swing.JMenuItem();
        consulta3 = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla2);

        Btncargar.setText("Buscar");
        Btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncargarActionPerformed(evt);
            }
        });

        jLabel1.setText("Límite inferior (por defecto está 50000): ");

        jMenu1.setText("Consultas");

        consulta1.setText("Consulta1");
        consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta1ActionPerformed(evt);
            }
        });
        jMenu1.add(consulta1);

        consulta2.setText("Consulta2");
        jMenu1.add(consulta2);

        consulta3.setText("Consulta3");
        consulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta3ActionPerformed(evt);
            }
        });
        jMenu1.add(consulta3);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(txtLimiInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(Btncargar)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btncargar)
                    .addComponent(jLabel1)
                    .addComponent(txtLimiInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta1ActionPerformed
        ReportesViewGuiConsulta1 reporte1 = new ReportesViewGuiConsulta1();
        reporte1.setVisible(true);
        reporte1.setSize(900,450);
        reporte1.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_consulta1ActionPerformed

    private void consulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta3ActionPerformed
        ReportesViewGuiConsulta3 reporte3 = new ReportesViewGuiConsulta3();
        reporte3.setVisible(true);
        reporte3.setSize(900,450);
        reporte3.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_consulta3ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void BtncargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncargarActionPerformed
        DefaultTableModel modeloTabla2 = new DefaultTableModel();
        Tabla2.setModel(modeloTabla2);
        modeloTabla2.addColumn("ID");
        modeloTabla2.addColumn("Valor");
        
        double limInf ;
        if(txtLimiInferior.getText().isEmpty()){
            limInf = 50_000d;
        }
        else{
            limInf = Double.parseDouble(txtLimiInferior.getText());
        }
        
        ReportesController reportesController = new ReportesController();
            List<DeudasPorProyectoVo> respuesta = reportesController.listarTotalAdeudadoProyectos(limInf);
            for (DeudasPorProyectoVo deuda : respuesta) {
                Object fila[] = new Object[2];
                fila[0] = deuda.getId();
                fila[1] = deuda.getValor();
                modeloTabla2.addRow(fila);
            }
    }//GEN-LAST:event_BtncargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesViewGuiConsulta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesViewGuiConsulta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesViewGuiConsulta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesViewGuiConsulta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesViewGuiConsulta2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btncargar;
    private javax.swing.JTable Tabla2;
    private javax.swing.JMenuItem consulta1;
    private javax.swing.JMenuItem consulta2;
    private javax.swing.JMenuItem consulta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem salir;
    private javax.swing.JTextField txtLimiInferior;
    // End of variables declaration//GEN-END:variables
}
